### ISSUE TITLE
Website should be served through TLS

### ISSUE THREAD

**Issue by graingert** [PyconUK/2017.pyconuk.org#3]
GitLab supports TLS out of the box. They do not support SSL.

https://about.gitlab.com/2016/04/11/tutorial-securing-your-gitlab-pages-with-tls-and-letsencrypt/

As an added bonus it will let you build using django-amber without having to push to branches etc.

![](https://3.bp.blogspot.com/-DG70U0Y-y9w/V9Cwuym53AI/AAAAAAAAAW0/6zO81T_hqWMjdAF_YYK7dfXV-26DL7OYACLcB/s1600/blog%2Bimage%2B2.png)

**Comment by inglesp** [comment]
Thanks for this @graingert -- we're aware of the problem (see also https://github.com/PyconUK/2016.pyconuk.org/issues/215...) but it's not a high priority for us.

We're unlikely to move to GitLab any time soon, since we're already set up to work with GitHub and it's a known place to raise bugs.

We've talked about hosting the site on AWS or running our own DO droplet, and while the technical work is minimal, I'm keen not to add more operational overhead to the volunteer team than we need to.

So we'll keep this issue open, but we might not end up addressing it any time soon.

**Comment by PeterJCLaw** [comment]
You might get some mileage out of using Cloudflare to proxy the site and thus provide HTTPS: https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b/477bc362e9430bf594a86a472c5808a1f2d85a17.
I'm not sure whether the upstream connection from Cloudflare to githhub pages would have secure, though given that you _can_ secure that link (https://help.github.com/articles/securing-your-github-pages-site-with-https/) it seems plausible that it would be.

**Comment by graingert** [comment]
Sadly you can't trick cloudflare into accepting a github.io certificate for
a custom domain.

**Comment by ghickman** [comment]
Now that GitHub Pages supports this I've enabled it for this deployment.
